# Generated by Django 5.1.2 on 2024-11-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Class", "0001_initial"),
        ("Students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Class.class",
            ),
        ),
    ]
